# Welcome to Jekyll!
#

# Site settings
title: Gigi Coghlan
owner: Gigi Coghlan # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: gigicoghlan6@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gigicoghlan.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/gigicoghlan
  linkedin-square: https://linkedin.com/in/gissele-coghlan-a977b71aa/
  email: /contact/gigicoghlan6@gmail.com
  instagram: https://www.instagram.com/gigihasart/?hl=en

# Build settings
markdown: kramdown
#sass:
#  style: compressed
